---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(CodeClanData)
```

```{r}
nhs_specialty <-  read_csv(here::here("../clean_data/nhs_speciality.csv"))
nhs_deprivation <- read_csv(here::here("../clean_data/nhs_deprivation.csv"))
nhs_age_sex <-  read_csv(here::here("../clean_data/nhs_age_sex.csv"))
```

```{r}
nhs_speciality %>%
  filter(location_name == "Scotland",
         admission_type == "All Inpatients and Day cases",
         specialty_name == "Respiratory Medicine",
         str_detect(quarter, "201[6-9]")) %>% 
  ggplot() +
  geom_line(aes(x = quarter, y = spells, group = 1)) +
  scale_y_continuous(breaks = seq(0, 10000, 500), limits = c(0, NA))

?scale_y_continuous
  

 aaa <- nhs_specialty %>% distinct(specialty_name) %>% pull()
```


```{r}
nhs_specialty %>%
  filter(location_name == "Scotland",
         admission_type == "All Inpatients",
         specialty_name == "Respiratory Medicine",
         str_detect(quarter, "201[6-9]")) %>% 
  ggplot() +
  geom_line(aes(x = quarter, y = spells, group = 1)) +
  scale_y_continuous(limits = c(0, NA))
```


```{r}
nhs_bed_occupancy <-  read_csv(here::here("../clean_data/nhs_bed_occupancy.csv"))
  
```

```{r}
nhs_bed_occupancy %>% 
  filter(location_name == "Scotland",
         str_detect(quarter, "201[6-9]"),
         specialty_name == "All Specialties") %>% 
  summarise(mean_bed_oc = mean(percentage_occupancy))
```



```{r}
nhs_bed_occupancy %>% distinct(specialty_name)

nhs_bed_occupancy %>% 
  filter(location_name == "Scotland",
         str_detect(quarter, "201[7-9]"),
         specialty_name == "All Acute") %>% 
  ggplot() +
  geom_line(aes(x = quarter, y = all_staffed_beddays, group = 1)) +
  geom_line(aes(x = quarter, y = 81.74, group = 1), colour = "red", size = 2) +
  scale_y_continuous(limits = c(NA, NA))
```

```{r}
nhs_stays_hb <- read_csv(here::here("../clean_data/nhs_speciality.csv"))
nhs_stays_hb %>% distinct(specialty_name)
nhs_bed_occupancy %>% distinct(specialty_name)

nhs_stays_hb %>% 
      filter(location_name == "Scotland",
             str_detect(quarter, "201[7-9]"),
             admission_type == "All Inpatients and Day cases",
             specialty_name == "Cardiology") %>% 
      ggplot() +
      geom_line(aes(x = quarter, y = spells, group = 1)) +
      geom_line(aes(x = quarter, y = 81.74, group = 1), colour = "red", size = 2) +
      scale_y_continuous(limits = c(NA, NA)) 
```

```{r}
nhs_stays_hb <- read_csv(here::here("../clean_data/nhs_deprivation.csv"))
```

```{r}
nhs_bed_occupancy %>% 
  filter(quarter == "2016 Q4",
         location_name == "Scotland",
         str_detect(specialty, "^[ACHJ]")) %>% 
  summarise(sum = sum(all_staffed_beddays))

nhs_bed_occupancy %>% 
  filter(quarter == "2016 Q4",
         location_name == "Scotland")
```

```{r}
nhs_bed_occupancy %>% 
  filter(specialty_name %in% (nhs_stays_hb %>% distinct(specialty_name) %>% pull()),
         location_name == "Scotland") %>% 
  distinct(specialty_name)

nhs_stays_hb %>% distinct(admission_type) %>% arrange(admission_type)
```

```{r}
nhs_stays_hb %>% 
  filter(location_name == "Scotland") %>% 
  group_by(specialty_name) %>% 
  summarise(sum(spells))

```

```{r}
specialties <- nhs_stays_hb %>% distinct(specialty_name) %>% pull()

nhs_bed_occupancy %>% 
        filter(location_name == "Scotland",
               specialty_name %in% specialties,
               str_detect(quarter, "201[7-9]")) %>%
        group_by(quarter) %>% 
        summarise(percentage_occupancy = sum(total_occupied_beddays) / sum(all_staffed_beddays) * 100)
```

